version: '2'
services:

    etcd0:
        image: quay.io/coreos/etcd:v3.2.5
        restart: always
        ports:
            - 23791:2379
            - 23801:2380
        volumes:
            - etcd0:/etcd_data
        environment:
            ETCD_NAME: etcd0-name
            ETCD_DATA_DIR: /etcd_data
            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://0.0.0.0:2380
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
            ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
            ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379

volumes:
  etcd0:
